### ISSUE TITLE
Import Data to Lichess4545.com regarding lonewolf season 1

### ISSUE THREAD

**Issue by Sebastien32** [Lichess4545/Chesster#348]
Contact Seb32 for spreadsheet via slack

**Comment by Sebastien32** [comment]
Actually it's quite possible i could do this myself through the dashboard. Will check this weekend.

**Comment by lakinwecker** [comment]
Should be possible. Either way, this ticket belongs on https://github.com/cyanfish/heltour, so I'm closing it here. :D

**Comment by Sebastien32** [comment]
Well would you look at that: https://github.com/cyanfish/heltour/issues/141

**Comment by lakinwecker** [comment]
lol
