### ISSUE TITLE
Change Chesster's welcome message to teams

### ISSUE THREAD

**Issue by MrScribblesChess** [Lichess4545/Chesster#349]
Hello! 

Chesster's first message to team channels says, in part:

`You need to pick a team captain and a team name by Aug 31.
Once you've chosen (or if you need help with anything), contact one of the moderators:
@tnan123 @sgis @MrScribbles @Tranzoo @Sesquipedalism @jcarmody @kraaft @erinyu @glbert @tsatsa64`

I request to change this part to:
`You need to pick a team captain and a team name by Aug 31. Once you've chosen (or if you need help with anything), please post `@chesster summon mods` in #general and one of them will message you. Please do not message the mods directly, wait for them to contact you first.`

Thanks for all you do for this league.

**Comment by lakinwecker** [comment]
I moved this to: https://github.com/cyanfish/heltour/issues/353 this message comes from the website.
