### ISSUE TITLE
Chesster warning message about games very close to deadline contain personal user information

### ISSUE THREAD

**Issue by hopffgam** [Lichess4545/Chesster#353]
When scheduling a game very close to the end of the round, chesster sends a warning message. That message seems to include the account name of the email address the player registered with. So, it can contain the real name of the player, instead of the slack name. The message should refer to the slack account name.
![Scheduling](https://user-images.githubusercontent.com/68183297/93490787-36584d80-f909-11ea-88c5-7b991c1e62b6.png)

**Comment by lakinwecker** [comment]
We should use this: https://github.com/Lichess4545/Chesster/blob/main/src/commands/scheduling.ts#L453-L455 

instead of: 
https://github.com/Lichess4545/Chesster/blob/main/src/commands/scheduling.ts#L403-L405
