### ISSUE TITLE
Chesster doesn't post games for alternates in their team channel

### ISSUE THREAD

**Issue by lakinwecker** [Lichess4545/Chesster#357]
The notification system mistakenly checks for the team from the player, and the alternate doesn't have a team, so it doesn't work. It should look up the pairing and figure out both teams from this.

**Comment by dombrno** [comment]
if you have a pointer to the place where the notification system checks for the team from the player, that will help, cheers!

**Comment by lakinwecker** [comment]
https://github.com/Lichess4545/Chesster/blob/72412bdf2d42e7f11d227a45e779878551f993a1/src/commands/subscription.ts#L421 is the function that's supposed to get the "Listeners" for a given game event.  It's  somewhere in here. Basically, we try and lookup the team by the player names, but we should probably try and find the pairing by the player names and then find the teams from that pairing.
