### ISSUE TITLE
Accept the 20+20 time control for games posted in #chess960games

### ISSUE THREAD

**Issue by Unclevinny** [Lichess4545/Chesster#399]
When players post their game in #chess960games, chesster replies:

> I am sorry, [@UncleVinny](https://lichess4545.slack.com/team/U39RGVDG9),  your post is not valid because the time control is incorrect.
> If this was a mistake, please correct it and try again. If intentional, please contact one of the moderators for review. Thank you.

I've looked through the code (as a scrub) and can't figure out where this validation is going wrong.

**Comment by mathgeek** [comment]
Fixed - discrepancy in the live config
